version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: hilaaba/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: hilaaba/foodgram_frontend:latest
    volumes:
      - result_build:/app/result_build/build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  database:
  result_build:
  redoc:
